package com.juniar.carrierhub.entity;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.juniar.carrierhub.entity.BarangEntity;
import com.juniar.carrierhub.entity.UserEntity;

import com.juniar.carrierhub.entity.BarangEntityDao;
import com.juniar.carrierhub.entity.UserEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig barangEntityDaoConfig;
    private final DaoConfig userEntityDaoConfig;

    private final BarangEntityDao barangEntityDao;
    private final UserEntityDao userEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        barangEntityDaoConfig = daoConfigMap.get(BarangEntityDao.class).clone();
        barangEntityDaoConfig.initIdentityScope(type);

        userEntityDaoConfig = daoConfigMap.get(UserEntityDao.class).clone();
        userEntityDaoConfig.initIdentityScope(type);

        barangEntityDao = new BarangEntityDao(barangEntityDaoConfig, this);
        userEntityDao = new UserEntityDao(userEntityDaoConfig, this);

        registerDao(BarangEntity.class, barangEntityDao);
        registerDao(UserEntity.class, userEntityDao);
    }
    
    public void clear() {
        barangEntityDaoConfig.clearIdentityScope();
        userEntityDaoConfig.clearIdentityScope();
    }

    public BarangEntityDao getBarangEntityDao() {
        return barangEntityDao;
    }

    public UserEntityDao getUserEntityDao() {
        return userEntityDao;
    }

}
